# map index 
tile_map = {
    
    (13, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"You see many cats.",
        "Type": "Interact",
        "Interaction Text": "silly grassland yay yay!",
        "Reward": "Potion",
        "Reward Amount": 2,
        "Reward Obtained": False,
        "Battle Complete": None,
    },
    
    (14, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (15, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (16, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (17, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },
    
    (18, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (19, 1): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (13, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (14, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (15, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },
    
    (16, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": None,
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (17, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Plain",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (18, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Shop",
        "Interaction Text": "None",
        "Reward": None,
        "Reward Amount": None,
        "Reward Obtained": None,
        "Battle Complete": None,
    },

    (19, 2): {
        "Location": "Kingdom Outskirts",
        "Name": "Grassland",
        "Description":"aaaaaaa",
        "Type": "Interact",
        "Interaction Text": "WOw theres a sword here",
        "Reward": "Greatsword",
        "Reward Amount": 1,
        "Reward Obtained": False,
        "Battle Complete": None,
    },
}